export const ROOMS = [
  {
    id: 'A646',
    name: 'A646 階梯型會議廳',
    theme: '地緣政治、軍事戰略、政策、經貿',
    presentations: [
      { session: 'S1', time: '10:05-10:20', presenter: '伯煜昆 Walker', topic: '臺灣政府如何維持現狀', '實習': '國策院' },
      { session: 'S1', time: '10:20-10:35', presenter: '宋詩琳 Priyanka', topic: '2016 年政黨輪替後民進黨與國民黨兩岸政策的差異性：國家認同與戰略思維的比較', '實習': '' },
      { session: 'S1', time: '10:35-10:50', presenter: '羅福山 Sean', topic: '美國科技巨頭對政府決策之影響及其對臺的利弊', '實習': '' },
      { session: 'S1', time: '10:50-11:05', presenter: '蘇蘭珺 Sophia', topic: '臺灣關鍵基礎設施與國家安全', '實習': '' },
      { session: 'S2', time: '11:15-11:30', presenter: '英慧 Cyrus', topic: '臺灣勞基法與加班現況', '實習': '' },
      { session: 'S2', time: '11:30-11:45', presenter: '郭恩美 Amy', topic: '美國關稅政策對臺灣農漁產品出口影響之分析', '實習': '' },
      { session: 'S2', time: '11:45-12:00', presenter: '淦波帆 Katelynn', topic: '中國「一帶一路」倡議對臺灣的影響', '實習': '' },
      { session: 'S2', time: '12:00-12:15', presenter: '何維明', topic: '伊朗戰爭的原因與影響', '實習': '' },
      { session: 'S3', time: '13:50-14:05', presenter: '伯煜昆 Walker', topic: '反送中之後香港人移民到國外：以台灣、加拿大、以及英國為比較分析', '實習': '' },
      { session: 'S3', time: '14:05-14:20', presenter: '馬麗莎 Alyssa', topic: '臺灣的城市外交--以桃園為例', '實習': '' },
      { session: 'S3', time: '14:20-14:35', presenter: '白敏樂 Emily', topic: '中國在拉丁美洲的軍民兩用基礎建設--以阿根廷烏肯省深空站為例', '實習': '' },
      { session: 'S4', time: '14:45-15:00', presenter: '英慧 Cyrus', topic: '金融資料分析過程', '實習': '碁石智庫' },
      { session: 'S4', time: '15:00-15:15', presenter: '賀新 Jaden', topic: '虛假訊息對臺灣關鍵基礎設施的威脅', '實習': '' },
      { session: 'S4', time: '15:15-15:30', presenter: '麥世寧 Sean', topic: '臺灣半總統制的理論與現實：從制度設計到政治運作的權責分析', '實習': '' },
    ],
  },
  {
    id: 'A604',
    name: 'A604 個案教室',
    theme: '心理、教育、人文藝術、行為分析',
    presentations: [
      { session: 'S1', time: '10:05-10:20', presenter: '林小聖 Sage', topic: '人際關係對小型設計公司的重要性', '實習': '黑田視覺整合' },
      { session: 'S1', time: '10:20-10:35', presenter: '范露莎 Larissa', topic: '自閉症患者從眾行為之社交偽裝的心理影響', '實習': '' },
      { session: 'S1', time: '10:35-10:50', presenter: '華美珍', topic: '自閉症兒童的學習過程', '實習': '' },
      { session: 'S1', time: '10:50-11:05', presenter: '竹麗 Julia', topic: '臺美大學生理財行為的比較', '實習': '' },
      { session: 'S2', time: '11:15-11:30', presenter: '柯海琳 Kailyn', topic: '城鄉差距與臺灣雙語教育成效之關聯', '實習': '' },
      { session: 'S2', time: '11:30-11:45', presenter: '江雨川 Emma', topic: '小團體策略對 ASD 學生情緒調節與人際互動之影響', '實習': '' },
      { session: 'S2', time: '11:45-12:00', presenter: '郭吉達 Gilda', topic: 'AI 語音合成中的「口音」與「偏見」', '實習': '' },
      { session: 'S2', time: '12:00-12:15', presenter: '梁安妮 Annie', topic: '以代理式人工智慧建構對話式購物推薦系統：以滑鼠選購情境為例', '實習': '' },
      { session: 'S3', time: '13:50-14:05', presenter: '范露莎 Larissa', topic: '自閉症患者在職場的溝通策略', '實習': '自閉症總會' },
      { session: 'S3', time: '14:05-14:20', presenter: '楊子璇 Elizabeth', topic: '臺灣的原住民語言復興運動', '實習': '' },
      { session: 'S3', time: '14:20-14:35', presenter: '貝責 Beyza', topic: '臺灣原住民如何使用藝術進行文化抵抗與保留', '實習': '' },
      { session: 'S4', time: '14:45-15:00', presenter: '柯海琳 Kailyn', topic: '博物館作為第二教室－故宮博物院的教育功能探討', '實習': '' },
      { session: 'S4', time: '15:00-15:15', presenter: '郭琳熙 Gwendolyn', topic: '走進青銅時代｜「赫列克蘇爾」的古代墳墓', '實習': '' },
      { session: 'S4', time: '15:15-15:30', presenter: '林小聖 Sage', topic: '比較臺美字型創作與產業概況', '實習': '' },
    ],
  },
  {
    id: 'A605',
    name: 'A605 個案教室',
    theme: 'AI、軟體、半導體、醫療、資安、環境',
    presentations: [
      { session: 'S1', time: '10:05-10:20', presenter: '彭毅 Brandon', topic: '網絡安全：無聲的守護者', '實習': '' },
      { session: 'S1', time: '10:20-10:35', presenter: '楊怡珠 Emma', topic: '非英語母語者學習編程的挑戰', '實習': '' },
      { session: 'S1', time: '10:35-10:50', presenter: '福媛芳 Emily', topic: '知己知彼：孫子兵法在網絡防禦中的運用', '實習': '' },
      { session: 'S1', time: '10:50-11:05', presenter: '徐芯怡 Katherine', topic: '醫療影像(X射線)與物質相互作用的屏蔽機制', '實習': '陽明交大' },
      { session: 'S2', time: '11:15-11:30', presenter: '何安娜 Anashelly', topic: '衰老對疫苗免疫反應的影響', '實習': '' },
      { session: 'S2', time: '11:30-11:45', presenter: '冉爍蕊 Carolyn', topic: '臺灣的垃圾管理制度', '實習': '' },
      { session: 'S2', time: '11:45-12:00', presenter: '金達 Tegan', topic: '人工智能對於會計產業的影響', '實習': '' },
      { session: 'S2', time: '12:00-12:15', presenter: '謝劉燁', topic: '心得分享--《淺談 AI 發展浪潮下企業營業秘密保護因應對策》', '實習': '' },
      { session: 'S3', time: '13:50-14:05', presenter: '徐芯怡 Katherine', topic: '美國與臺灣醫療制度的比較--以闌尾炎為例', '實習': '' },
      { session: 'S3', time: '14:05-14:20', presenter: '羅福山 Sean', topic: '防禦科技產業供應鏈的全球化', '實習': '工研院' },
      { session: 'S3', time: '14:20-14:35', presenter: '蘇蘭珺 Sophia', topic: '防禦科技產業供應鏈的全球化', '實習': '工研院' },
      { session: 'S4', time: '14:45-15:00', presenter: '詹彬禮 Brooklyn', topic: 'AI 強化的自主移動機器人：基於視覺的決策系統', '實習': '' },
      { session: 'S4', time: '15:00-15:15', presenter: '楊怡珠 Emma', topic: '共享開發文件在軟體發展中的重要性', '實習': '崧旭資訊' },
      { session: 'S4', time: '15:15-15:30', presenter: '郭恩美 Amy', topic: '人工智能在招募流程中的應用', '實習': '金融研訓院' },
      { session: 'S4', time: '15:30-15:45', presenter: '彭毅 Brandon', topic: '產業銜接', '實習': '台北市電腦公會' },
    ],
  },
];
