export const styles = {
  app: {
    minHeight: '100vh',
    background: 'linear-gradient(135deg, #e8f0fe 0%, #f0f4f8 50%, #e8f4fd 100%)',
    fontFamily: "'Noto Sans TC', 'PingFang TC', 'Microsoft JhengHei', sans-serif",
  },
  header: {
    background: 'linear-gradient(90deg, #1a73e8 0%, #0d47a1 100%)',
    color: '#fff',
    padding: '16px 20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    boxShadow: '0 2px 8px rgba(26,115,232,0.4)',
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },
  headerTitle: {
    fontSize: '1.2rem',
    fontWeight: 700,
    letterSpacing: '0.02em',
  },
  headerSub: {
    fontSize: '0.75rem',
    opacity: 0.85,
    marginTop: 2,
  },
  headerBtn: {
    background: 'rgba(255,255,255,0.15)',
    border: '1px solid rgba(255,255,255,0.3)',
    borderRadius: 8,
    color: '#fff',
    padding: '6px 10px',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: 6,
    fontSize: '0.8rem',
    transition: 'background 0.2s',
  },
  main: {
    maxWidth: 640,
    margin: '0 auto',
    padding: '20px 16px 60px',
  },
  formBanner: {
    width: '100%',
    aspectRatio: '16 / 5',
    borderRadius: 12,
    objectFit: 'cover',
    objectPosition: 'center',
    display: 'block',
    marginBottom: 16,
    boxShadow: '0 2px 16px rgba(0,0,0,0.08)',
    background: '#e8f0fe',
  },
  card: {
    background: '#fff',
    borderRadius: 16,
    boxShadow: '0 2px 16px rgba(0,0,0,0.08)',
    padding: '20px',
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: '1rem',
    fontWeight: 700,
    color: '#1a237e',
    marginBottom: 14,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  select: {
    width: '100%',
    padding: '12px 14px',
    border: '2px solid #e0e7ff',
    borderRadius: 10,
    fontSize: '0.95rem',
    color: '#333',
    background: '#fff',
    appearance: 'none',
    backgroundImage:
      "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 24 24' fill='none' stroke='%231a73e8' stroke-width='2'%3E%3Cpolyline points='6 9 12 15 18 9'%3E%3C/polyline%3E%3C/svg%3E\")",
    backgroundRepeat: 'no-repeat',
    backgroundPosition: 'right 12px center',
    cursor: 'pointer',
    outline: 'none',
    transition: 'border-color 0.2s',
    marginBottom: 10,
  },
  scoreRow: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: 14,
    gap: 12,
  },
  scoreLabel: {
    fontSize: '0.9rem',
    color: '#444',
    width: 100,
    flexShrink: 0,
  },
  scoreButtons: {
    display: 'flex',
    gap: 4,
    flexWrap: 'wrap',
  },
  scoreBtn: (active, compact = false) => ({
    width: compact ? 30 : 32,
    height: compact ? 30 : 32,
    borderRadius: 6,
    border: active ? '2px solid #1a73e8' : '2px solid #e0e7ff',
    background: active ? 'linear-gradient(135deg, #1a73e8, #0d47a1)' : '#f5f8ff',
    color: active ? '#fff' : '#666',
    fontSize: compact ? '0.8rem' : '0.85rem',
    fontWeight: active ? 700 : 400,
    cursor: 'pointer',
    transition: 'all 0.15s',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  }),
  textarea: {
    width: '100%',
    padding: '12px',
    border: '2px solid #e0e7ff',
    borderRadius: 10,
    fontSize: '0.95rem',
    resize: 'vertical',
    minHeight: 80,
    outline: 'none',
    fontFamily: 'inherit',
    transition: 'border-color 0.2s',
    boxSizing: 'border-box',
  },
  primaryBtn: {
    width: 'min(100%, 360px)',
    padding: '11px 12px',
    background: 'linear-gradient(90deg, #1a73e8 0%, #0d47a1 100%)',
    color: '#fff',
    border: 'none',
    borderRadius: 12,
    fontSize: '0.92rem',
    fontWeight: 700,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    transition: 'opacity 0.2s, transform 0.1s',
    marginTop: 8,
    marginLeft: 'auto',
    marginRight: 'auto',
  },
  toast: (show) => ({
    position: 'fixed',
    bottom: 24,
    left: '50%',
    transform: show ? 'translateX(-50%) translateY(0)' : 'translateX(-50%) translateY(100px)',
    background: '#1b5e20',
    color: '#fff',
    padding: '14px 24px',
    borderRadius: 12,
    fontWeight: 600,
    fontSize: '0.95rem',
    boxShadow: '0 4px 20px rgba(0,0,0,0.25)',
    transition: 'transform 0.4s cubic-bezier(0.175, 0.885, 0.32, 1.275)',
    zIndex: 9999,
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  }),
  overlay: {
    position: 'fixed',
    inset: 0,
    background: 'rgba(0,0,0,0.5)',
    zIndex: 200,
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  modal: {
    background: '#fff',
    borderRadius: '20px 20px 0 0',
    padding: '24px 20px',
    width: '100%',
    maxWidth: 640,
    maxHeight: '80vh',
    overflowY: 'auto',
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: '1.1rem',
    fontWeight: 700,
    color: '#1a237e',
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  rankItem: (rank) => ({
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '12px',
    borderRadius: 10,
    marginBottom: 8,
    background: rank === 1 ? '#fff8e1' : rank === 2 ? '#f5f5f5' : rank === 3 ? '#fbe9e7' : '#fafafa',
    border: rank === 1 ? '1px solid #ffc107' : '1px solid #eee',
  }),
  rankNum: (rank) => ({
    width: 28,
    height: 28,
    borderRadius: '50%',
    background: rank === 1 ? '#ffc107' : rank === 2 ? '#9e9e9e' : rank === 3 ? '#ff7043' : '#e0e0e0',
    color: rank <= 3 ? '#fff' : '#666',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontWeight: 700,
    fontSize: '0.85rem',
    flexShrink: 0,
  }),
  footer: {
    textAlign: 'center',
    color: '#9e9e9e',
    fontSize: '0.75rem',
    marginTop: 32,
  },
};
